In [33]:
#!pip install --upgrade numpy
!pip install numpy==1.24.3
!python -V
np.__version__

     ---------------------------------------- 0.0/14.8 MB ? eta -:--:--
     ---------------------------------------- 0.1/14.8 MB 3.6 MB/s eta 0:00:05
      --------------------------------------- 0.2/14.8 MB 2.9 MB/s eta 0:00:06
      --------------------------------------- 0.3/14.8 MB 3.2 MB/s eta 0:00:05
     - -------------------------------------- 0.4/14.8 MB 2.3 MB/s eta 0:00:07
     - -------------------------------------- 0.5/14.8 MB 2.4 MB/s eta 0:00:06
     -- ------------------------------------- 0.8/14.8 MB 2.8 MB/s eta 0:00:05
     -- ------------------------------------- 1.0/14.8 MB 3.2 MB/s eta 0:00:05
     --- ------------------------------------ 1.2/14.8 MB 3.4 MB/s eta 0:00:04
     --- ------------------------------------ 1.3/14.8 MB 3.5 MB/s eta 0:00:04
     --- ------------------------------------ 1.5/14.8 MB 3.3 MB/s eta 0:00:05
     ---- ----------------------------------- 1.7/14.8 MB 3.6 MB/s eta 0:00:04
     ----- ---------------------------------- 2.0/14.8 MB 3

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
gensim 4.3.0 requires FuzzyTM>=0.4.0, which is not installed.
tables 3.8.0 requires blosc2~=2.0.0, which is not installed.
tables 3.8.0 requires cython>=0.29.21, which is not installed.
transformers 2.1.1 requires sentencepiece, which is not installed.


Python 3.11.4


'1.24.3'

In [19]:
# numpy 패키지를 np라는 이름으로 불러옵니다.
import numpy as np

# 1차원 배열 생성
arr1 = np.array([1, 2, 3])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3]
<class 'numpy.ndarray'>
(3,)


In [28]:
arr2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2)
print(type(arr2))
print(arr2.shape)
print(arr2.size)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>
(3, 3)
9


In [45]:
# numpy 패키지를 np라는 이름으로 불러옵니다.
import numpy as np

# 1차원 배열 생성
arr1 = np.array([1, 2, 3])
print(arr1)
# 2차원 배열 생성
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2)
print(arr2.size)
print(len(arr2))
# 배열의 크기 확인
print("Shape of arr1:", arr1.shape)
print("Shape of arr2:", arr2.shape)

# 배열의 원소 타입 확인
print("Data type of arr1:", arr1.dtype)
print("Data type of arr2:", arr2.dtype)

# 범위를 지정하여 배열 생성 
arr3 = np.arange(10) 
print(arr3)
print(arr3.size)
print(len(arr3))
# 특정 값으로 채워진 배열 생성 (0부터 시작해서 크기가 (3,4)인 행렬을 만들고 모든 원소를 7로 초기화)
arr4 = np.full((3,4),7) 
print(arr4)
print(arr4.size)
print(len(arr4))



[1 2 3]
[[1 2 3]
 [4 5 6]]
6
2
Shape of arr1: (3,)
Shape of arr2: (2, 3)
Data type of arr1: int32
Data type of arr2: int32
[0 1 2 3 4 5 6 7 8 9]
10
10
[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]
12
3


In [48]:
arr = np.zeros((3,3))
print(arr)

arr = np.ones((3,3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [53]:
arr = np.array([[1,2,3,4,5,6],[1,2,3,4,5,6]])
print(arr)
print(arr.shape)
arr.reshape(3,4)


[[1 2 3 4 5 6]
 [1 2 3 4 5 6]]
(2, 6)


array([[1, 2, 3, 4],
       [5, 6, 1, 2],
       [3, 4, 5, 6]])

In [58]:
arr1 = np.eye(3)
print(arr1.shape)
print(arr1)
arr2 = np.full((3,3),2)
print(arr2)

(3, 3)
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[2 2 2]
 [2 2 2]
 [2 2 2]]


In [63]:
arr3 = arr1 * arr2
print(arr3)
arr4 = np.dot(arr1,arr2)
print(arr4)

[[2. 0. 0.]
 [0. 2. 0.]
 [0. 0. 2.]]
[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


| 함수                    | 설명                                                                                             | 예제                            |
|-----------------------|------------------------------------------------------------------------------------------------|---------------------------------|
| `np.array(iterable)` | 주어진 `iterable`에서 NumPy 배열을 생성합니다.                                                       | `arr = np.array([1, 2, 3])`      |
| `np.zeros(shape)`     | 모든 요소가 0인 지정된 모양(shape)의 배열을 생성합니다.                                      | `zeros_arr = np.zeros((2, 3))`  |
| `np.ones(shape)`      | 모든 요소가 1인 지정된 모양(shape)의 배열을 생성합니다.                                      | `ones_arr = np.ones((3, 3))`    |
| `np.empty(shape)`     | 초기화되지 않은 지정된 모양(shape)의 배열을 생성합니다.                                    | `empty_arr = np.empty((2, 2))`  |
| `np.arange(start, stop, step)` | 주어진 범위에서 일정한 간격으로 값을 생성하여 배열을 만듭니다. | `range_arr = np.arange(0, 10, 2)` |
| `np.linspace(start, stop, num)` | 주어진 범위에서 일정한 개수(num)의 값을 생성하여 배열을 만듭니다. | `linspace_arr = np.linspace(0, 1, 5)` |
| `np.eye(N)`            | N x N 크기의 단위 행렬(대각선 요소가 1이고 나머지는 0)을 생성합니다.                          | `identity_matrix = np.eye(3)`  |
| `np.random.rand(shape)` | 지정된 모양(shape)의 무작위 값 배열을 생성합니다.                                      | `rand_arr = np.random.rand(3, 3)` |
| `np.reshape(array, new_shape)` | 배열의 모양(shape)을 변경합니다. | `reshaped_arr = np.reshape(arr, (3, 1))` |
| `np.transpose(array)` | 배열의 전치(Transpose) 버전을 생성합니다. | `transposed_arr = np.transpose(arr)` |
| `np.max(array)`        | 배열 내의 최댓값을 반환합니다.                                                               | `maximum = np.max(arr)`         |
| `np.min(array)`        | 배열 내의 최솟값을 반환합니다.                                                               | `minimum = np.min(arr)`         |
| `np.mean(array)`       | 배열의 평균값을 반환합니다.                                                                   | `mean_value = np.mean(arr)`     |
| `np.sum(array)`        | 배열의 모든 요소의 합을 반환합니다.                                                           | `total_sum = np.sum(arr)`       |
| `np.dot(array1, array2)` | 두 배열의 행렬 곱을 계산합니다.                                                              | `result = np.dot(matrix1, matrix2)` |


In [79]:
arr = np.arange(0,20,2)
print(arr)
arr = np.arange(1,10,0.5)
print(arr)
arr = np.linspace(0,100,5)
print(arr)
arr = np.arange(1,37)
arr1 = arr.reshape(6,6)
print(arr1)
arr2 = arr.reshape(-1,1)
print(arr2)
arr3 = arr.reshape(-1,2)
print(arr3)
arr4 = arr.reshape(3,-2)
print(arr4)

[ 0  2  4  6  8 10 12 14 16 18]
[1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5 9.  9.5]
[  0.  25.  50.  75. 100.]
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]
[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]
 [24]
 [25]
 [26]
 [27]
 [28]
 [29]
 [30]
 [31]
 [32]
 [33]
 [34]
 [35]
 [36]]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]
 [15 16]
 [17 18]
 [19 20]
 [21 22]
 [23 24]
 [25 26]
 [27 28]
 [29 30]
 [31 32]
 [33 34]
 [35 36]]
[[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]
 [25 26 27 28 29 30 31 32 33 34 35 36]]


In [85]:
a=np.ones((4,4))
b=np.arange(4)
c=b.reshape(4,1)
print(a+b)
print(a+c)
print(b+c)

[[1. 2. 3. 4.]
 [1. 2. 3. 4.]
 [1. 2. 3. 4.]
 [1. 2. 3. 4.]]
[[1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]
 [4. 4. 4. 4.]]
[[0 1 2 3]
 [1 2 3 4]
 [2 3 4 5]
 [3 4 5 6]]


In [6]:
import numpy as np
a = np.array([1,2,3,4,5,6,7,8,9])
print(a)
print(a[4:8])
print(a[5:-1])
print(a[1:3:2])
print(a[3:8:2])

[1 2 3 4 5 6 7 8 9]
[5 6 7 8]
[6 7 8]
[2]
[4 6 8]


In [14]:
a=np.arange(1,10).reshape(3,3)
print(a)
print(a[0])
print(a[1])
print(a[2])
print(a[0][1])
print(a[0:1])
print(a[0:2])
print(a[0:3])
print(a[0:-1])
print(a[:,1:])
print(a[:1,:2])
print(a[1:2,1:2])
print(a[2,:])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3]
[4 5 6]
[7 8 9]
2
[[1 2 3]]
[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]]
[[2 3]
 [5 6]
 [8 9]]
[[1 2]]
[[5]]
[7 8 9]


In [15]:
a=np.arange(1,26).reshape(5,5)
print(a)
print(a[:3,1:3])
print(a[0:3][1:3])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
[[ 2  3]
 [ 7  8]
 [12 13]]
[[ 6  7  8  9 10]
 [11 12 13 14 15]]


In [24]:
a=np.arange(1,26).reshape(5,5)
print(a)
a1 = a[:3,:3]
print(a1)
a1[1][1]=100
print(a1)
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
[[ 1  2  3]
 [ 6  7  8]
 [11 12 13]]
[[  1   2   3]
 [  6 100   8]
 [ 11  12  13]]
[[  1   2   3   4   5]
 [  6 100   8   9  10]
 [ 11  12  13  14  15]
 [ 16  17  18  19  20]
 [ 21  22  23  24  25]]


In [23]:
b=np.arange(1,26).reshape(5,5)
print(b)
b1 = b[:3,:3].copy()
print(b1)
b1[1][1]=100
print(b1)
print(b)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
[[ 1  2  3]
 [ 6  7  8]
 [11 12 13]]
[[  1   2   3]
 [  6 100   8]
 [ 11  12  13]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [32]:
a=np.arange(1,25).reshape(2,3,4)
print(a)
print(a.ndim)
print(a[0])
print(a[0,2])
print(a[1, :,:2])

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
3
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[ 9 10 11 12]
[[13 14]
 [17 18]
 [21 22]]
