In [2]:
!pip install pandas

In [7]:
import pandas as pd
import numpy as np

a = [1,2,3,4,5]
ar = pd.Series(a)
print(ar)
type(ar)

0    1
1    2
2    3
3    4
4    5
dtype: int64


pandas.core.series.Series

In [18]:
ar = pd.Series(a,index=list('abcde'))
print(ar[:])
print(ar[3:])
print(ar[:3])
print(ar[:-1])
print(ar[1:-1])

a    1
b    2
c    3
d    4
e    5
dtype: int64
d    4
e    5
dtype: int64
a    1
b    2
c    3
dtype: int64
a    1
b    2
c    3
d    4
dtype: int64
b    2
c    3
d    4
dtype: int64


In [25]:
arview = ar['c':'e']
print(arview)
arview['e']=500
print(ar)

c      3
d      4
e    500
dtype: int64
a      1
b      2
c      3
d      4
e    500
dtype: int64


In [29]:
np.may_share_memory(ar, arview)

True

In [35]:
print(ar.index)
print(ar)
ar=ar.rename(index={'e':'z'})
print(ar)

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')
a      1
b      2
c      3
d      4
e    500
dtype: int64
a      1
b      2
c      3
d      4
z    500
dtype: int64


In [38]:
arcopy = ar.copy()
print(arcopy)
np.may_share_memory(arcopy, ar)

a      1
b      2
c      3
d      4
z    500
dtype: int64


False

In [44]:
arview = ar[3:]
print(arview)
print(np.may_share_memory(arview, ar))
arview['f']=6
print(arview)
np.may_share_memory(arview, ar)


d      4
z    500
dtype: int64
True
d      4
z    500
f      6
dtype: int64


False

In [45]:
ar

a      1
b      2
c      3
d      4
z    500
dtype: int64

In [48]:
ar['5']=200
ar


a      1
b      2
c      3
d      4
z    500
5    200
dtype: int64

In [49]:
test = ar.to_frame()
type(test)

pandas.core.frame.DataFrame

In [52]:
a = pd.DataFrame([[1,2,3,4,5],[6,7,8,9],[10,11,12,13,14,15]])
print(a)
a = pd.DataFrame([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
print(a)

    0   1   2   3     4     5
0   1   2   3   4   5.0   NaN
1   6   7   8   9   NaN   NaN
2  10  11  12  13  14.0  15.0
    0   1   2   3   4
0   1   2   3   4   5
1   6   7   8   9  10
2  11  12  13  14  15


In [68]:
_df = pd.DataFrame(np.arange(1,16).reshape(3,5))
print(_df)
print(_df.ndim)
print(_df.size)
print(_df.values)
print(_df.index)

    0   1   2   3   4
0   1   2   3   4   5
1   6   7   8   9  10
2  11  12  13  14  15
2
15
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
RangeIndex(start=0, stop=3, step=1)


In [74]:
df = pd.DataFrame(np.arange(1,16).reshape(3,5),index=list('abc'), columns=list('ABCDE'))
print(df)
print(df.size)
print(df.shape)
print(df.values)
print(df.index)
print(df.columns)

    A   B   C   D   E
a   1   2   3   4   5
b   6   7   8   9  10
c  11  12  13  14  15
15
(3, 5)
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
Index(['a', 'b', 'c'], dtype='object')
Index(['A', 'B', 'C', 'D', 'E'], dtype='object')


In [75]:
print(df.dtypes)

A    int32
B    int32
C    int32
D    int32
E    int32
dtype: object


In [78]:
print(df['A'])  

a     1
b     6
c    11
Name: A, dtype: int32


In [86]:
print(df.loc['a'])
print(type(df.loc['b']))
print(df.loc['b'].dtype)

A    1
B    2
C    3
D    4
E    5
Name: a, dtype: int32
<class 'pandas.core.series.Series'>
int32


In [97]:
print(df.loc['c', :])
print(df.loc['c', 'A':'C'])
print(type(df.loc['c', 'A':'C']))

A    11
B    12
C    13
D    14
E    15
Name: c, dtype: int32
A    11
B    12
C    13
Name: c, dtype: int32
<class 'pandas.core.series.Series'>


In [101]:
print(df)
print(df.loc['a':'b','B':])
print(type(df.loc['a':'b','B':]))

    A   B   C   D   E
a   1   2   3   4   5
b   6   7   8   9  10
c  11  12  13  14  15
   B  C  D   E
a  2  3  4   5
b  7  8  9  10
<class 'pandas.core.frame.DataFrame'>


In [106]:
b = df.copy()
b1 = b.loc['a':,'A':'B']
print(b1)
print(np.may_share_memory(b,b1))
b1.loc['a','B'] = 1500
b

    A   B
a   1   2
b   6   7
c  11  12
True


A     B   C   D   E
a   1  1500   3   4   5
b   6     7   8   9  10
c  11    12  13  14  15

In [108]:
b1['B']=1000
b1

A     B
a   1  1000
b   6  1000
c  11  1000

In [109]:
b

A     B   C   D   E
a   1  1500   3   4   5
b   6     7   8   9  10
c  11    12  13  14  15

In [110]:
np.may_share_memory(b,b1)

False

In [121]:
print(df)
print(df.iloc[0])
print(df.iloc[-1])
print(df.iloc[-1,2:])
print(df.iloc[:,2:4])

    A   B   C   D   E
a   1   2   3   4   5
b   6   7   8   9  10
c  11  12  13  14  15
A    1
B    2
C    3
D    4
E    5
Name: a, dtype: int32
A    11
B    12
C    13
D    14
E    15
Name: c, dtype: int32
C    13
D    14
E    15
Name: c, dtype: int32
    C   D
a   3   4
b   8   9
c  13  14


In [124]:
_data = np.arange(1,10).reshape(3,3)
_index = list('abc')
_columns = list('ABC')
df = pd.DataFrame(data = _data, index = _index, columns= _columns)
df

A  B  C
a  1  2  3
b  4  5  6
c  7  8  9

In [128]:
_serise = pd.DataFrame({'A':pd.Series([1,2,3,4],dtype='int'),'B':pd.Series([5,6,7,8],dtype='float')})
_serise

A    B
0  1  5.0
1  2  6.0
2  3  7.0
3  4  8.0

In [129]:
_list = pd.DataFrame({'점수':[90,80,12,12],'학점':['A','B','C','f']})
_list

점수 학점
0  90  A
1  80  B
2  12  C
3  12  f

In [130]:
_df

0   1   2   3   4
0   1   2   3   4   5
1   6   7   8   9  10
2  11  12  13  14  15

In [146]:
b.dtypes
b2=b.iloc[:,:3]
b2


A     B   C
a   1  1500   3
b   6     7   8
c  11    12  13

In [148]:
b3 = b2.astype({'A':np.int64})
b3.dtypes

A    int64
B    int32
C    int32
dtype: object

In [152]:
pa= np.arange(1,26).reshape(5,5)
pa

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [153]:
pa[0,2]

3

In [154]:
pa[[0,2]]

array([[ 1,  2,  3,  4,  5],
       [11, 12, 13, 14, 15]])

In [157]:
temp = pa[[2,3]]
print(temp[:,2:-1])

[[13 14]
 [18 19]]


In [160]:
pa[np.ix_([2,3],[2,3])]

array([[13, 14],
       [18, 19]])